name: Continous Delivery

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - .github/**
            - src/**
            - tests/**

env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    packages: write
    contents: read

jobs:
    publish-gpr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1
              with:
                  node-version: 16
                  cache: 'yarn'

            - run: yarn
            - run: yarn build

            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  registry: https://npm.pkg.github.com

            - if: steps.publish.outputs.type != 'none'
              run: |
                  echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
