name: Continous Delivery

on:
    workflow_dispatch:
    push:
        branches:
            - main

#env:
#    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: write
    id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publish-gpr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: pnpm
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: pnpm install
              
            - run: pnpm build

            - name: Create Release Pull Request
              id: changesets
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              with:
                  # This expects you to have a script called release which does a build for your packages and calls changeset publish
                  publish: pnpm release

            - name: Send a Slack notification if a publish happens
              if: steps.changesets.outputs.published == 'true'
              # You can do something when a publish happens.
              run: echo "A new version of ${GITHUB_REPOSITORY} was published!"
