name: Continous Delivery

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    packages: write
    contents: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publish-gpr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.1

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: pnpm

            - run: pnpm i
            - run: pnpm build

            - name: Create Release Pull Request
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  # This expects you to have a script called release which does a build for your packages and calls changeset publish
                  publish: pnpm release

            - if: steps.publish.outputs.type != 'none'
              run: |
                  echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
