name: Continous Delivery

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    packages: write
    contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publish-gpr:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: 'npm'

            - name: Install Turbo
              run: npm install -g turbo

            - run: npm install
            - run: npm run build

            - name: Create Release Pull Request
              uses: changesets/action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                # This expects you to have a script called release which does a build for your packages and calls changeset publish
                publish: npm run release

            - if: steps.publish.outputs.type != 'none'
              run: |
                  echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
