name: Continous Integration

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: read

jobs:
    lint_run:
        name: Run Lint and Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.1

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: pnpm

            - name: Install dependencies
              run: pnpm i

            - run: node -p 'os.cpus()'
            - run: pnpm lint
            # - run: pnpm test
            - run: pnpm build
